version: '2'
services:
    sponge_forge:
        image: nobitagamer/sponge-forge
        container_name: forge
        environment:
            - "MINECRAFT_PORT:25566"
            - "MINECRAFT_EULA:true"
            - "MINECRAFT_MAXHEAP:4096M"
            - "FORGE_VERSION:1.10.2-12.18.2.2171"
            - "SPONGE_VERSION:1.10.2-2171-5.1.0-BETA-2010"
        expose:
            - "25566"
        ports:
            - "25566:25566"
        stdin_open: true
        tty: true
        volumes:
            - ./data:/forge:rw